### ISSUE TITLE
[Issue]: bankAccountExtractJob fails for a US seller with a CA bank account

### ISSUE THREAD

**Issue by guillauc** [paypal/mirakl-hyperwallet-connector#110]
### Describe the Issue

**ERROR:**
app_1  | {
app_1  |   "errorCode" : "EXTERNAL_ACCOUNT_TYPE_NOT_SUPPORTED",
app_1  |   "errorMessage" : "The bank account information provided is not configured for your program.",
app_1  |   "exceptionMessage" : "The bank account information provided is not configured for your program.",
app_1  |   "responseStatusCode" : "400",
app_1  |   "responseMessage" : "Bad Request",
app_1  |   "responseBody" : "{\n  \"errors\" : [ {\n
    \"message\" : \"The bank account information provided is not configured for your program.\",\n    \"code\" : \"EXTERNAL_ACCOUNT_TYPE_NOT_SUPPORTED\"\n  } ]\n}\n",
app_1  |   "errorDetailList" : [ {
app_1  |     "code" : "EXTERNAL_ACCOUNT_TYPE_NOT_SUPPORTED",
app_1  |     "message" : "The bank account information provided is not configured for your program."
app_1  |   } ]
app_1  | }

[US seller CAD Bank Account Issue.docx](https://github.com/paypal/mirakl-hyperwallet-connector/files/10448650/US.seller.CAD.Bank.Account.Issue.docx)
[bankaccountextract_errorlog.txt](https://github.com/paypal/mirakl-hyperwallet-connector/files/10448655/bankaccountextract_errorlog.txt)

### Environment

Test/UAT

### Version

4.17.0

### Expected Behavior

Expected to have a US Seller with a Canadian Bank Account, both in MIRAKL and Hyperwallet

### Actual Behavior

The Bank Account is not created in Hyperwallet when the Country of the Seller is United States and the Bank Account is a Canadian Account.

### Steps to Reproduce

1. US Seller / Shop created in Mirakl;
2. Professional Seller Extract Job Sucessfull;
3. Seller created in Hyperwallet;
4. CA Bank Account created in Mirakl for that same seller;
5. Bank account Extract Job Fails with "EXTERNAL_ACCOUNT_TYPE_NOT_SUPPORTED";

### Relevant log output

```shell
app_1  | 18-01-2023 15:46:55.951 [HyperwalletMiraklScheduler_Worker-1] INFO   com.paypal.infrastructure.job.listener.JobExecutionInformationListener - Started [bankAccountExtractJob] at 2023-01-18T15:46:55.951807309
app_1  | 18-01-2023 15:46:56.010 [HyperwalletMiraklScheduler_Worker-1] INFO  {"id":"34f94e1b-9b0e-42f7-a82a-feceace0ce5c","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Starting processing of job
app_1  | 18-01-2023 15:46:56.010 [HyperwalletMiraklScheduler_Worker-1] INFO  {"id":"34f94e1b-9b0e-42f7-a82a-feceace0ce5c","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Starting extraction of items to be processed
app_1  | 18-01-2023 15:46:56.011 [HyperwalletMiraklScheduler_Worker-1] INFO  {"id":"34f94e1b-9b0e-42f7-a82a-feceace0ce5c","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Retrieving shops since Wed Jan 18 15:43:55 UTC 2023
app_1  | 18-01-2023 15:46:56.238 [HyperwalletMiraklScheduler_Worker-1] INFO  {"id":"34f94e1b-9b0e-42f7-a82a-feceace0ce5c","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Shops retrieved []
app_1  | 18-01-2023 15:46:56.239 [HyperwalletMiraklScheduler_Worker-1] INFO  {"id":"34f94e1b-9b0e-42f7-a82a-feceace0ce5c","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Retrieving shops since Wed Jan 18 15:43:55 UTC 2023
app_1  | 18-01-2023 15:46:56.319 [HyperwalletMiraklScheduler_Worker-1] INFO  {"id":"34f94e1b-9b0e-42f7-a82a-feceace0ce5c","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl - Shops retrieved [2084]
app_1  | 18-01-2023 15:46:56.390 [HyperwalletMiraklScheduler_Worker-1] INFO  {"id":"34f94e1b-9b0e-42f7-a82a-feceace0ce5c","subtype":"BankAccountExtractBatchJob","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Retrieved the following number of items to be processed: 1
app_1  | 18-01-2023 15:46:56.408 [HyperwalletMiraklScheduler_Worker-1] INFO  {"id":"34f94e1b-9b0e-42f7-a82a-feceace0ce5c","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2084","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Processing item of type BankAccount with id: 2084
app_1  | 18-01-2023 15:46:57.335 [HyperwalletMiraklScheduler_Worker-1] ERROR {"id":"34f94e1b-9b0e-42f7-a82a-feceace0ce5c","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2084","type":"BatchJob"} com.paypal.sellers.bankaccountextract.service.strategies.AbstractHyperwalletBankAccountRetryApiStrategy - Bank account not created or updated for seller with clientId [2084].
app_1  | {
app_1  |   "errorCode" : "EXTERNAL_ACCOUNT_TYPE_NOT_SUPPORTED",
app_1  |   "errorMessage" : "The bank account information provided is not configured for your program.",
app_1  |   "exceptionMessage" : "The bank account information provided is not configured for your program.",
app_1  |   "responseStatusCode" : "400",
app_1  |   "responseMessage" : "Bad Request",
app_1  |   "responseBody" : "{\n  \"errors\" : [ {\n    \"message\" : \"The bank account information provided is not configured for your program.\",\n    \"code\" : \"EXTERNAL_ACCOUNT_TYPE_NOT_SUPPORTED\"\n  } ]\n}\n",
app_1  |   "errorDetailList" : [ {
app_1  |     "code" : "EXTERNAL_ACCOUNT_TYPE_NOT_SUPPORTED",
app_1  |     "message" : "The bank account information provided is not configured for your program."
app_1  |   } ]
app_1  | }
app_1  | com.hyperwallet.clientsdk.HyperwalletException: The bank account information provided is not configured for your program.
app_1  |        at com.hyperwallet.clientsdk.util.HyperwalletApiClient.checkErrorResponse(HyperwalletApiClient.java:147)
app_1  |        at com.hyperwallet.clientsdk.util.HyperwalletApiClient.processResponse(HyperwalletApiClient.java:122)
app_1  |        at com.hyperwallet.clientsdk.util.HyperwalletApiClient.post(HyperwalletApiClient.java:96)
app_1  |        at com.hyperwallet.clientsdk.Hyperwallet.createBankAccount(Hyperwallet.java:1810)
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.HyperWalletCreateBankAccountServiceStrategyBankAccount.callHyperwalletAPI(HyperWalletCreateBankAccountServiceStrategyBankAccount.java:50)
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.AbstractHyperwalletBankAccountRetryApiStrategy.execute(AbstractHyperwalletBankAccountRetryApiStrategy.java:52)
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.HyperWalletCreateBankAccountServiceStrategyBankAccount.callSuperExecute(HyperWalletCreateBankAccountServiceStrategyBankAccount.java:64)
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.HyperWalletCreateBankAccountServiceStrategyBankAccount.execute(HyperWalletCreateBankAccountServiceStrategyBankAccount.java:39)
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.HyperWalletCreateBankAccountServiceStrategyBankAccount.execute(HyperWalletCreateBankAccountServiceStrategyBankAccount.java:19)
app_1  |        at com.paypal.infrastructure.strategy.SingleAbstractStrategyExecutor.execute(SingleAbstractStrategyExecutor.java:17)
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.HyperWalletBankAccountStrategyExecutor.callSuperExecute(HyperWalletBankAccountStrategyExecutor.java:48)
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.HyperWalletBankAccountStrategyExecutor.execute(HyperWalletBankAccountStrategyExecutor.java:44)
app_1  |        at com.paypal.sellers.batchjobs.bankaccount.BankAccountExtractBatchJobItemProcessor.processItem(BankAccountExtractBatchJobItemProcessor.java:38)
app_1  |        at com.paypal.sellers.batchjobs.bankaccount.BankAccountExtractBatchJobItemProcessor.processItem(BankAccountExtractBatchJobItemProcessor.java:13)
app_1  |        at com.paypal.infrastructure.batchjob.AbstractBatchJob.processItem(AbstractBatchJob.java:44)
app_1  |        at com.paypal.infrastructure.batchjob.BatchJobExecutor.processItem(BatchJobExecutor.java:86)
app_1  |        at com.paypal.infrastructure.batchjob.BatchJobExecutor.lambda$execute$0(BatchJobExecutor.java:27)
app_1  |        at java.base/java.util.ArrayList.forEach(Unknown Source)
app_1  |        at com.paypal.infrastructure.batchjob.BatchJobExecutor.execute(BatchJobExecutor.java:27)
app_1  |        at com.paypal.infrastructure.batchjob.quartz.QuartzBatchJobAdapter.execute(QuartzBatchJobAdapter.java:33)
app_1  |        at com.paypal.infrastructure.batchjob.quartz.AbstractBatchJobSupportQuartzJob.executeBatchJob(AbstractBatchJobSupportQuartzJob.java:20)
app_1  |        at com.paypal.sellers.jobs.BankAccountExtractJob.execute(BankAccountExtractJob.java:28)
app_1  |        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
app_1  |        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
app_1  | 18-01-2023 15:46:57.360 [HyperwalletMiraklScheduler_Worker-1] ERROR {"id":"34f94e1b-9b0e-42f7-a82a-feceace0ce5c","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2084","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - Failed processing item of type BankAccount with id: 2084
app_1  | com.paypal.infrastructure.exceptions.HMCHyperwalletAPIException: An error has occurred while invoking Hyperwallet API
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.AbstractHyperwalletBankAccountRetryApiStrategy.execute(AbstractHyperwalletBankAccountRetryApiStrategy.java:65)
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.HyperWalletCreateBankAccountServiceStrategyBankAccount.callSuperExecute(HyperWalletCreateBankAccountServiceStrategyBankAccount.java:64)
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.HyperWalletCreateBankAccountServiceStrategyBankAccount.execute(HyperWalletCreateBankAccountServiceStrategyBankAccount.java:39)
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.HyperWalletCreateBankAccountServiceStrategyBankAccount.execute(HyperWalletCreateBankAccountServiceStrategyBankAccount.java:19)
app_1  |        at com.paypal.infrastructure.strategy.SingleAbstractStrategyExecutor.execute(SingleAbstractStrategyExecutor.java:17)
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.HyperWalletBankAccountStrategyExecutor.callSuperExecute(HyperWalletBankAccountStrategyExecutor.java:48)
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.HyperWalletBankAccountStrategyExecutor.execute(HyperWalletBankAccountStrategyExecutor.java:44)
app_1  |        at com.paypal.sellers.batchjobs.bankaccount.BankAccountExtractBatchJobItemProcessor.processItem(BankAccountExtractBatchJobItemProcessor.java:38)
app_1  |        at com.paypal.sellers.batchjobs.bankaccount.BankAccountExtractBatchJobItemProcessor.processItem(BankAccountExtractBatchJobItemProcessor.java:13)
app_1  |        at com.paypal.infrastructure.batchjob.AbstractBatchJob.processItem(AbstractBatchJob.java:44)
app_1  |        at com.paypal.infrastructure.batchjob.BatchJobExecutor.processItem(BatchJobExecutor.java:86)
app_1  |        at com.paypal.infrastructure.batchjob.BatchJobExecutor.lambda$execute$0(BatchJobExecutor.java:27)
app_1  |        at java.base/java.util.ArrayList.forEach(Unknown Source)
app_1  |        at com.paypal.infrastructure.batchjob.BatchJobExecutor.execute(BatchJobExecutor.java:27)
app_1  |        at com.paypal.infrastructure.batchjob.quartz.QuartzBatchJobAdapter.execute(QuartzBatchJobAdapter.java:33)
app_1  |        at com.paypal.infrastructure.batchjob.quartz.AbstractBatchJobSupportQuartzJob.executeBatchJob(AbstractBatchJobSupportQuartzJob.java:20)
app_1  |        at com.paypal.sellers.jobs.BankAccountExtractJob.execute(BankAccountExtractJob.java:28)
app_1  |        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
app_1  |        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
app_1  | Caused by: com.hyperwallet.clientsdk.HyperwalletException: The bank account information provided is not configured for your program.
app_1  |        at com.hyperwallet.clientsdk.util.HyperwalletApiClient.checkErrorResponse(HyperwalletApiClient.java:147)
app_1  |        at com.hyperwallet.clientsdk.util.HyperwalletApiClient.processResponse(HyperwalletApiClient.java:122)
app_1  |        at com.hyperwallet.clientsdk.util.HyperwalletApiClient.post(HyperwalletApiClient.java:96)
app_1  |        at com.hyperwallet.clientsdk.Hyperwallet.createBankAccount(Hyperwallet.java:1810)
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.HyperWalletCreateBankAccountServiceStrategyBankAccount.callHyperwalletAPI(HyperWalletCreateBankAccountServiceStrategyBankAccount.java:50)
app_1  |        at com.paypal.sellers.bankaccountextract.service.strategies.AbstractHyperwalletBankAccountRetryApiStrategy.execute(AbstractHyperwalletBankAccountRetryApiStrategy.java:52)
app_1  |        ... 18 common frames omitted
app_1  | 18-01-2023 15:46:57.361 [HyperwalletMiraklScheduler_Worker-1] INFO  {"id":"34f94e1b-9b0e-42f7-a82a-feceace0ce5c","subtype":"BankAccountExtractBatchJob","itemType":"BankAccount","itemId":"2084","type":"BatchJob"} com.paypal.observability.batchjoblogging.listeners.BatchJobLoggingListener - 0 items processed successfully. 1 items failed. 0 items remaining
```

**Comment by max6001** [comment]
Hi @guillauc 

Thanks for reaching out and providing such detailed explanations of the encountered issue.

When you state: "Seller created in Hyperwallet;"
Are you using a single program or multi program on Hyperwallet side?
If multi program could you please let me know in which program the seller is created in Hyperwallet?

if you don't have a clue about the program structure used, simply provide the value for hw-program showed in the Mirakl shop view of the impacted seller (it should be either "DEFAULT" or another value).

Thanks in advance,

Best,

**Comment by guillauc** [comment]
Hi,

Thanks for getting back to me quickly.

The hw-program that we use is “DEFAULT”.

Thanks,

Guillaume Côté  | AnalystE PROGRAMMEUR/SYSTÈMES PRINCIPAL | Sr. Programmer/System Analyst
***@***.******@***.***>  | T 514.384.1140 :: 23466 |  W WWW.REITMANSCANADALIMITEE.COM<http://reitmanscanadalimitee.com/>

250, RUE SAUVÉ OUEST / WEST, MONTRÉAL (QUÉBEC) CANADA  H3L 1Z2
***@***.***

Ce message est confidentiel et peut contenir des informations qui sont privilégiées. Si vous avez reçu ce courriel par erreur,
veuillez en informer l'expéditeur par retour de courriel, supprimer ce message et en détruire toutes les copies ou pièces jointes.

This e-mail is confidential and may contain information that is privileged. If you have received this in error please notify
the sender by return email, delete this message and destroy any copies or attachments.

**Comment by max6001** [comment]
Hi @guillauc 

Sorry for the delay.

The issue you're encountering is due to a misconfiguration on your Hyperwallet instance.
I would recommend to get in touch with Hyperwallet to get this issue resolved.

Thanks for your understanding and have a great day,

Best,

**Comment by guillauc** [comment]
Hi @max6001,

Before opening an issue, I did verify with Hyperwallet. 

Would it be possible to have a little more details around the misconfiguration on our Hyperwallet instance?

Thank you.

**Comment by max6001** [comment]
@guillauc 

"The issue is happening because each merchant has a set of configurations that drives what bank accounts can be created based on country / currency. In order to fix your problem, you need to work with someone who was access to the HW back office and get that person to update the External Account Configuration for that merchant and enable Canadian Bank Accounts"

**Comment by max6001** [comment]
Thanks @kshunt-paypal for the added information.
When the bank account type = IBAN, the bank account country sent to Hyperwallet is automatically set based on the first two letters of the IBAN. For example FR32546454233645 would have bank account country = France.
However, when the bank account type = ABA, CA, UK (different from IBAN format), the bank account country sent to Hyperwallet is taken from the Mirakl shop country.

We are going to change that behaviour and release a new version -next week to the latest- in order to set the bank account country based on the bank account type.

Sorry for the inconvenience.

Best,

**Comment by kshunt-paypal** [comment]
Thanks for confirming @max6001! Will you please update this ticket once it's complete? 

@guillauc - tagging you to ensure you've seen the above note about the fix and estimated time for delivery.

**Comment by guillauc** [comment]
Thank you @javierpoloe2y!

Greatly appreciated, I will test this as soon as possible.

@guillauc
