### ISSUE TITLE
Exception while processing Payments notifications

### ISSUE THREAD

**Issue by satheshsoundar** [paypal/mirakl-hyperwallet-connector#21]
Hi Team,
We have upgraded to the latest version and getting below exception while processing Payments notification.

com.mirakl.client.core.exception.MiraklApiException: [400] Error with field accounting_documents.invoice_id. Please check the field datatype
	at com.mirakl.client.core.internal.util.ResponseHelper.checkStatus(ResponseHelper.java:40) ~[mirakl-sdk-core-4.10.0.jar:na]
	at com.mirakl.client.core.AbstractMiraklApiClient.put(AbstractMiraklApiClient.java:378) ~[mirakl-sdk-core-4.10.0.jar:na]
	at com.mirakl.client.mmp.core.MiraklMarketplacePlatformFrontOperatorApiClient.confirmAccountingDocumentPayment(MiraklMarketplacePlatformFrontOperatorApiClient.java:174) ~[mmp-sdk-common-front-operator-4.10.0.jar:na]
	at com.paypal.invoices.paymentnotifications.service.AcceptedPaymentNotificationStrategy.execute(AcceptedPaymentNotificationStrategy.java:48) ~[main/:na]
	at com.paypal.invoices.paymentnotifications.service.AcceptedPaymentNotificationStrategy.execute(AcceptedPaymentNotificationStrategy.java:27) ~[main/:na]
	at com.paypal.infrastructure.strategy.SingleAbstractStrategyExecutor.execute(SingleAbstractStrategyExecutor.java:17) ~[main/:na]
	at com.paypal.invoices.paymentnotifications.service.impl.PaymentNotificationServiceImpl.processPaymentNotification(PaymentNotificationServiceImpl.java:33) ~[main/:na]
	at com.paypal.invoices.paymentnotifications.listeners.PaymentListener.onApplicationEvent(PaymentListener.java:31) ~[main/:na]
	at com.paypal.invoices.paymentnotifications.listeners.PaymentListener.onApplicationEvent(PaymentListener.java:15) ~[main/:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.6.jar:5.3.6]
	at com.paypal.notifications.services.sender.AbstractHMCEventSender.execute(AbstractHMCEventSender.java:22) ~[main/:na]
	at com.paypal.notifications.services.sender.PaymentSender.execute(PaymentSender.java:16) ~[main/:na]
	at com.paypal.infrastructure.strategy.SingleAbstractStrategyExecutor.execute(SingleAbstractStrategyExecutor.java:17) ~[main/:na]
	at com.paypal.notifications.services.impl.NotificationServiceImpl.processNotification(NotificationServiceImpl.java:38) ~[main/:na]
	at com.paypal.notifications.controllers.IncomingHyperwalletNotificationWebhookMockController.receiveIncomingNotification(IncomingHyperwalletNotificationWebhookMockController.java:38) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.6.jar:5.3.6]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) ~[tomcat-embed-core-9.0.45.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.6.jar:5.3.6]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.45.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.6.jar:5.3.6]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.6.jar:5.3.6]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) ~[spring-boot-actuator-2.4.5.jar:2.4.5]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.6.jar:5.3.6]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

Please help me to solve this issue

Regards,
Sathesh.

**Comment by kcarta** [comment]
Hi @satheshsoundar, thank you for raising this issue and for the full stacktrace.

I see the top-level error is being reporting via the Mirakl SDK as:
`com.mirakl.client.core.exception.MiraklApiException: [400] Error with field accounting_documents.invoice_id. Please check the field datatype`

Can you please provide me some information into the action that generated this error? Were you trying to see the connector mark an invoice as `Paid` in Mirakl? If so, it appears Mirakl is rejecting the `invoice_id` field specifically, is there a chance this could have an invalid or incorrectly-formatted value?

**Comment by satheshsoundar** [comment]
Hi @kcarta,
We are getting this issue while setting the payment as confirmed. Below is the payload we sending to Hyperwallet Connector.
`{
   "token":"wbh-xxxxxxx-xxxxxx-xxxx-xxx",
   "type":"PAYMENTS.UPDATED.STATUS.COMPLETED",
   "createdOn":"Nov 10, 2021, 6:19:42 PM",
   "object":{
      "token":"pmt-xxxxx-xxxxx-xxxxx-xxxxx-xxx",
      "status":"COMPLETED",
      "createdOn":"2021-11-10T16:41:35",
      "amount":"10.39",
      "currency":"EUR",
      "clientPaymentId":"DGLDE0000011111",
      "purpose":"OTHER",
      "expiresOn":"2022-05-09T16:41:35",
      "destinationToken":"trm-xxxxx-xxxxx-xxxx-xxx",
      "programToken":"prg-xxxx-xxxxx-xxxxx-xxxx"
   }

> }`

AcceptedPaymentNotificationStrategy.java -> execute(method)

Client Id is set to Invoice Id in MiraklAccountingDocumentPaymentConfirmation object and MiraklConfirmAccountingDocumentPaymentRequest is created with list of MiraklAccountingDocumentPaymentConfirmation.

**Comment by kcarta** [comment]
@satheshsoundar, thank you for sharing this payload. 
Do you know how the `clientPaymentId` was set as `DGLDE0000011111`? Mirakl will be expecting a purely numeric ID, to correspond to the numeric ID of the accounting document that you are attempting to mark as `Paid`.

**Comment by kcarta** [comment]
Closing this issue as it has been resolved
