### ISSUE TITLE
[Issue]: HMC Version upgrade to 4.12.0 -Issue 

### ISSUE THREAD

**Issue by siprapattanaik** [paypal/mirakl-hyperwallet-connector#49]
### Describe the Issue

We recently upgraded the HMC version to 4.12.0.With every run of bank account-extract job we are seeing the null pointer exception while retrieving the shop IDs

### Environment

Test/UAT

### Version

4.12.0

### Relevant log output

```shell
2022-07-01 12:01:00.152 EDT
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "com.mirakl.client.mmp.domain.shop.MiraklShops.getShops()" is null
	at com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl.internalExtractIndividuals(MiraklSellersExtractServiceImpl.java:164) ~[sellers-4.12.0-plain.jar!/:na]
	at com.paypal.sellers.sellersextract.service.impl.MiraklSellersExtractServiceImpl.extractIndividuals(MiraklSellersExtractServiceImpl.java:70) ~[sellers-4.12.0-plain.jar!/:na]
	at com.paypal.sellers.batchjobs.bankaccount.BankAccountExtractBatchJobItemsExtractor.getItems(BankAccountExtractBatchJobItemsExtractor.java:35) ~[sellers-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.AbstractDeltaBatchJobItemsExtractor.getItems(AbstractDeltaBatchJobItemsExtractor.java:44) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.AbstractBatchJob.getItems(AbstractBatchJob.java:36) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.BatchJobExecutor.retrieveBatchItems(BatchJobExecutor.java:42) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.BatchJobExecutor.execute(BatchJobExecutor.java:23) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.quartz.QuartzBatchJobAdapter.execute(QuartzBatchJobAdapter.java:33) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.quartz.AbstractBatchJobSupportQuartzJob.executeBatchJob(AbstractBatchJobSupportQuartzJob.java:20) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.sellers.jobs.BankAccountExtractJob.execute(BankAccountExtractJob.java:28) ~[sellers-4.12.0-plain.jar!/:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar!/:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.2.ja
```

**Comment by javierpoloe2y** [comment]
Hi @siprapattanaik, this null pointer happens because there are no shops updated in Mirakl, and the Mirakl SDK `MiraklShops.getShops()` returns a null value while the code was expecting an empty list.

This means that this null pointer doesn't have any impact on the bank account extraction process since there aren't any modifications in Mirakl to be processed. If there were any updates to be processed the null pointer wouldn't happen. So you shouldn't worry too much about it.

However, the "no shops updated" scenario should have been properly handled by the code, and we will provide a fix in the future to avoid this type of error.
