### ISSUE TITLE
[Issue]: HMC upgrade to 4.12.0 for MiraklAPI exception , SocketTimeout

### ISSUE THREAD

**Issue by siprapattanaik** [paypal/mirakl-hyperwallet-connector#50]
### Describe the Issue

We recently upgraded to 4.12.0.We are seeing below exception on every run.However we do not know which job is causing this issue as there is no info in logs.
com.mirakl.client.core.exception.MiraklApiException: Exception occurred during request
	at com.mirakl.client.core.exception.MiraklApiException.ioException(MiraklApiException.java:22) ~[mirakl-sdk-core-4.10.0.jar!/:na]
	at com.mirakl.client.core.AbstractMiraklApiClient.get(AbstractMiraklApiClient.java:239) ~[mirakl-sdk-core-4.10.0.jar!/:na]
	at com.mirakl.client.core.AbstractMiraklApiClient.get(AbstractMiraklApiClient.java:230) ~[mirakl-sdk-core-4.10.0.jar!/:na]
	at com.paypal.infrastructure.sdk.mirakl.impl.MiraklMarketplacePlatformOperatorApiClientWrapperImpl.getHmcMiraklInvoices(MiraklMarketplacePlatformOperatorApiClientWrapperImpl.java:31) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.sdk.mirakl.impl.MiraklMarketplacePlatformOperatorApiClientWrapperImpl.getInvoices(MiraklMarketplacePlatformOperatorApiClientWrapperImpl.java:27) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.invoices.invoicesextract.service.mirakl.impl.AbstractAccountingDocumentsExtractServiceImpl.getInvoicesForDateAndType(AbstractAccountingDocumentsExtractServiceImpl.java:92) ~[invoices-4.12.0-plain.jar!/:na]
	at com.paypal.invoices.invoicesextract.service.mirakl.impl.AbstractAccountingDocumentsExtractServiceImpl.extractAccountingDocuments(AbstractAccountingDocumentsExtractServiceImpl.java:62) ~[invoices-4.12.0-plain.jar!/:na]
	at com.paypal.invoices.batchjobs.invoices.InvoicesExtractBatchJobItemsExtractor.getItems(InvoicesExtractBatchJobItemsExtractor.java:35) ~[invoices-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.AbstractDeltaBatchJobItemsExtractor.getItems(AbstractDeltaBatchJobItemsExtractor.java:44) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.AbstractBatchJob.getItems(AbstractBatchJob.java:36) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.BatchJobExecutor.retrieveBatchItems(BatchJobExecutor.java:42) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.BatchJobExecutor.execute(BatchJobExecutor.java:23) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.quartz.QuartzBatchJobAdapter.execute(QuartzBatchJobAdapter.java:33) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.quartz.AbstractBatchJobSupportQuartzJob.executeBatchJob(AbstractBatchJobSupportQuartzJob.java:20) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.invoices.jobs.InvoicesExtractJob.execute(InvoicesExtractJob.java:43) ~[invoices-4.12.0-plain.jar!/:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar!/:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.2.jar!/:na]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[na:na]
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:981) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1434) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1038) ~[na:na]
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[httpcore-4.4.15.jar!/:4.4.15]
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[httpcore-4.4.15.jar!/:4.4.15]
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[httpcore-4.4.15.jar!/:4.4.15]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.15.jar!/:4.4.15]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[httpcore-4.4.15.jar!/:4.4.15]
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.15.jar!/:4.4.15]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.15.jar!/:4.4.15]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar!/:4.5.13]
	at com.mirakl.client.core.AbstractMiraklApiClient.performRequest(AbstractMiraklApiClient.java:257) ~[mirakl-sdk-core-4.10.0.jar!/:na]
	at com.mirakl.client.core.AbstractMiraklApiClient.get(AbstractMiraklApiClient.java:236) ~[mirakl-sdk-core-4.10.0.jar!/:na]
	... 15 common frames omitted

### Environment

Test/UAT

### Version

4.12.0

### Relevant log output

```shell
com.mirakl.client.core.exception.MiraklApiException: Exception occurred during request
	at com.mirakl.client.core.exception.MiraklApiException.ioException(MiraklApiException.java:22) ~[mirakl-sdk-core-4.10.0.jar!/:na]
	at com.mirakl.client.core.AbstractMiraklApiClient.get(AbstractMiraklApiClient.java:239) ~[mirakl-sdk-core-4.10.0.jar!/:na]
	at com.mirakl.client.core.AbstractMiraklApiClient.get(AbstractMiraklApiClient.java:230) ~[mirakl-sdk-core-4.10.0.jar!/:na]
	at com.paypal.infrastructure.sdk.mirakl.impl.MiraklMarketplacePlatformOperatorApiClientWrapperImpl.getHmcMiraklInvoices(MiraklMarketplacePlatformOperatorApiClientWrapperImpl.java:31) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.sdk.mirakl.impl.MiraklMarketplacePlatformOperatorApiClientWrapperImpl.getInvoices(MiraklMarketplacePlatformOperatorApiClientWrapperImpl.java:27) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.invoices.invoicesextract.service.mirakl.impl.AbstractAccountingDocumentsExtractServiceImpl.getInvoicesForDateAndType(AbstractAccountingDocumentsExtractServiceImpl.java:92) ~[invoices-4.12.0-plain.jar!/:na]
	at com.paypal.invoices.invoicesextract.service.mirakl.impl.AbstractAccountingDocumentsExtractServiceImpl.extractAccountingDocuments(AbstractAccountingDocumentsExtractServiceImpl.java:62) ~[invoices-4.12.0-plain.jar!/:na]
	at com.paypal.invoices.batchjobs.invoices.InvoicesExtractBatchJobItemsExtractor.getItems(InvoicesExtractBatchJobItemsExtractor.java:35) ~[invoices-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.AbstractDeltaBatchJobItemsExtractor.getItems(AbstractDeltaBatchJobItemsExtractor.java:44) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.AbstractBatchJob.getItems(AbstractBatchJob.java:36) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.BatchJobExecutor.retrieveBatchItems(BatchJobExecutor.java:42) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.BatchJobExecutor.execute(BatchJobExecutor.java:23) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.quartz.QuartzBatchJobAdapter.execute(QuartzBatchJobAdapter.java:33) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.infrastructure.batchjob.quartz.AbstractBatchJobSupportQuartzJob.executeBatchJob(AbstractBatchJobSupportQuartzJob.java:20) ~[infrastructure-4.12.0-plain.jar!/:na]
	at com.paypal.invoices.jobs.InvoicesExtractJob.execute(InvoicesExtractJob.java:43) ~[invoices-4.12.0-plain.jar!/:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar!/:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.2.jar!/:na]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[na:na]
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:981) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1434) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1038) ~[na:na]
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[httpcore-4.4.15.jar!/:4.4.15]
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[httpcore-4.4.15.jar!/:4.4.15]
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[httpcore-4.4.15.jar!/:4.4.15]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.15.jar!/:4.4.15]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[httpcore-4.4.15.jar!/:4.4.15]
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.15.jar!/:4.4.15]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.15.jar!/:4.4.15]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar!/:4.5.13]
	at com.mirakl.client.core.AbstractMiraklApiClient.performRequest(AbstractMiraklApiClient.java:257) ~[mirakl-sdk-core-4.10.0.jar!/:na]
	at com.mirakl.client.core.AbstractMiraklApiClient.get(AbstractMiraklApiClient.java:236) ~[mirakl-sdk-core-4.10.0.jar!/:na]
	... 15 common frames omitted
```

**Comment by javierpoloe2y** [comment]
Hi @siprapattanaik, this error is happening during the execution of the invoice extract job (is something that can be found inspecting the stack trace, where you can find references to `InvoicesExtractBatchJobItemsExtractor`).

It looks like a temporary problem with the connection to Mirakl, as it is giving you a `java.net.SocketTimeoutException: Read timed out`. If you execute manually the job for the same date range it should work.

Also, my recommendation is to update to release 4.13.0, since it automatically adjusts the date range for the extraction jobs to include the date range of past failed jobs. This means that for example if the invoice extraction job for today fails, tomorrow's execution will try to extract the invoices for both today and tomorrow.

**Comment by max6001** [comment]
Hi @siprapattanaik
Are you still witnessing that issue after updating to the latest version of the connector?
Thanks in advance for your return,
Best,

**Comment by max6001** [comment]
No response regarding that particular issue.
Closing but do not hesitate to reach out if you ever need any help!
